replicaCount: 1

image:
  repository: harbor.phink8s.com/library/ip-tracker
  pullPolicy: Always
  # Tag is set from Chart.yaml appVersion

namespace: web-app

secretsName: iptracker-secrets

service:
  service: ip-tracker-svc
  port: 80

ingress:
  enabled: true
  host: iptracker.phink8s.com
  secretName: wildcard-phink8s.com-tls

# CronJob settings
cron:
  enabled: true
  baseUrl: https://iptracker.phink8s.com/vm.php
  # schedule: "*/15 * * * *"     # Every 15 minutes
  schedule: "0 * * * *"    # Every hour (example)
  ntfyTopic: "pbs"    # Change to your ntfy topic